### ISSUE TITLE
ジュリアが検索できない

### ISSUE THREAD

**Issue by fvh-P** [imas/imasparql#153]
[P向け名刺管理サービス](https://ncm.fvhp.net)の担当アイドル登録にim@sparqlのデータを使わせていただいているのですが、アイドル名を検索するときに、例えば「あ」で検索すると、名前に「あ」を含むアイドルのうちジュリアだけが引っ掛かりません。(天海春香、アスラン=BBⅡ世、エミリースチュアートなどその他のアイドルは(おそらく)全員検索できています。)

検索のために投げているクエリは以下の通りです。
```
PREFIX schema: <http://schema.org/>
PREFIX imas: <https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#>
SELECT distinct ?name 
WHERE { ?s imas:nameKana|schema:name ?o;
        ?p imas:Idol.
        FILTER(regex(str(?o), "あ")).
        ?s schema:name ?name.}
order by(?name)
```

データが間違っているのか私のクエリが悪いのか分からないのですが、よろしくお願いいたします。

**Comment by crssnky** [comment]
ジュリアは本名がわからないので、schema:nameは空にしてあります。
schema:alternateNameには「ジュリア」があるのでそちらから取得してください。

この理論でいくと、アスランがschema:nameで取れてしまうのはおかしいな....

**Comment by crssnky** [comment]
まだ途中書きですが、こちらのクエリの部分を参考にしていただければ。
https://doc.crssnky.xyz/imasparql/GettingStarted/4.html

**Comment by fvh-P** [comment]
> schema:alternateNameには「ジュリア」があるのでそちらから取得してください。

情報ありがとうございます。クエリは書けました。

ただ、他のアイドルには存在する平仮名による表記がジュリアにはなく、平仮名で検索できないという問題があります。平仮名による表記を追加していただくことは可能ですか。

**Comment by fvh-P** [comment]
#154 で解決いたしました。ありがとうございました。
