### ISSUE TITLE
「趣味：なし」のアイドルの表記統一

### ISSUE THREAD

**Issue by gomao9** [imas/imasparql#217]
現在、プロフィール上の趣味が「なし」となっているアイドルは、以下の3名です。

- 双葉杏
- ジュリア
- 都築圭

このうち、双葉杏は`imas:Hobby`が「なし」となっていますが、ジュリアと都築圭の2名は`imas:Hobby`が定義されていません。
「なし」と表記するか、未定義とするか、どちらかに統一すべきと考えます。

個人的には、プロフィールに「趣味」欄がないアイドルと区別するために、「なし」表記で統一するほうが良いと思います。

**Comment by crssnky** [comment]
定義します！
