### ISSUE TITLE
黛冬優子の紹介文が変わっている

### ISSUE THREAD

**Issue by gomao9** [imas/imasparql#227]
[黛 冬優子 \(まゆずみ ふゆこ\) \| アイドルマスター シャイニーカラーズ\(シャニマス\)](https://shinycolors.idolmaster.jp/idol/unit5/fuyuko.html)
``` diff
- 常に控えめな笑顔で、清楚な女の子。可愛いものが大好きで、周囲への気配りもできるため人に好かれる性格。専門学校1年生。
+ 常に控えめな笑顔で、清楚に見える女の子。可愛いものが大好きで、周囲への気配りをするなど人に好かれるように振る舞う。専門学校1年生。
```
ゲーム内でプロデュースできるようになったことで紹介文が変わったようです。

`清楚な女の子` -> `清楚に見える女の子`
`周囲への気配りもできるため人に好かれる性格` -> `周囲への気配りをするなど人に好かれるように振る舞う`

im@sparqlとしてはどちらを正とするのがいいでしょうか。
公式サイトの最新の記述を採用するのが自然？

**Comment by crssnky** [comment]
公式の最新を採用という考えでOKです！
僕Pとしても、本当の彼女のままでもトップアイドルになることを応援していきたいですね📣
