### ISSUE TITLE
クエリ試すエリアをリッチにする

### ISSUE THREAD

**Issue by crssnky** [imas/imasparql#232]

**Comment by crssnky** [comment]
http://yasqe.yasgui.org/

**Comment by crssnky** [comment]
YASQE、日本語変数が使えないことに気付いた
もう既に色々なところで「日本語変数使えるんすよ～」って言ってしまってるので断念

**Comment by foooomio** [comment]
これ良さそうですね。日本語変数も対応してます。
https://sparql-support.dbcls.jp/sparql-support_j.html

**Comment by foooomio** [comment]
@crssnky YASGUI、日本語変数とくに問題なく使えているように見えるのですが、動きませんでしたか？

[DEMO](http://yasgui.org/#query=PREFIX+imas%3A+%3Chttps%3A%2F%2Fsparql.crssnky.xyz%2Fimasrdf%2FURIs%2Fimas-schema.ttl%23%3E%0APREFIX+foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%0ASELECT+%3F%E5%90%8D%E5%89%8D+%3F%E5%B9%B4%E9%BD%A2%0AWHERE+%7B%0A++%3F%E4%B8%BB%E8%AA%9E+a+imas%3AIdol+%3B%0A++++++rdfs%3Alabel+%3F%E5%90%8D%E5%89%8D+%3B%0A++++++foaf%3Aage+%3F%E5%B9%B4%E9%BD%A2+.%0A%7D%0AORDER+BY+%3F%E5%B9%B4%E9%BD%A2%0ALIMIT+20&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fsparql.crssnky.xyz%2Fspql%2Fimas%2Fquery&requestMethod=POST&tabTitle=Query&headers=%7B%7D&outputFormat=table)

ちなみに、YASGUI と SPARQL support ともに CodeMirror に起因する Mobile Safari の入力の問題があって、こちらを適用する必要があります。

[CodeMirrorでスマホからの日本語入力をなんとかする - Qiita](https://qiita.com/ttakuru88/items/e363267772cacf4c1fa2)

**Comment by crssnky** [comment]
ピコプラSPACEで打ちましょう
https://space.pikopikopla.net/
