### ISSUE TITLE
アイドル名のschema:name

### ISSUE THREAD

**Issue by crssnky** [imas/imasparql#245]
某所にて
> アイドルとしての登録名はロコやジュリアであるので、schema:name はアイドルが通常使用している名称がいいのではないかと考えてます。判断が分かれるところですが… アイマスの世界の外に目を向けると、たとえば麻倉ももさんは芸名だと思いますが、本名ではないから schema:name にはふさわしくない、とはならないと思うんですよ。
それと実用上の問題で、ジュリアを結果に含めつつロコとエミリーが重複しないようにクエリを書くのが難しいという問題もあります。

との意見をいただきました。
たしかにアイドルとしての活動名(カードに書いてある名前？)がschema:nameとして登録されているべきだと感じました。

**Comment by crssnky** [comment]
そういう修正をしていきたいですが、ロコみたいに活動名の他に本名がある人は、どのような語彙に格納するのが良いんでしょう。いっそ作る？

**Comment by crssnky** [comment]
某所2
> DBPedia-Japaneseは「名前」と「本名」を別のプロパティに分けてましたね( `prop-ja:名前` と `prop-ja:本名` )
もし分けるのだとしたら、各ゲームのカード記載の名前を `schema:name` 、本名を `imas:realName` とかにするのがしっくりくるかなーと思ってたりします:thinking_face:
この場合、「ロコ」や「エミリー」は `schema:name` になり、「ジュリア」の `imas:realName` は存在しない扱いになる感じです(本名不詳なので):thinking_face:

**Comment by foooomio** [comment]
まとめている最中ですが、とりあえずリストアップしておきます。

- [schema:alternateName を持つアイドル](https://sparql.crssnky.xyz/spql/imas/query?force-accept=text%2Fplain&query=PREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0APREFIX%20imas%3A%20%3Chttps%3A%2F%2Fsparql.crssnky.xyz%2Fimasrdf%2FURIs%2Fimas-schema.ttl%23%3E%0ASELECT%20%3Falt%0AWHERE%20%7B%0A%20%20%3Fs%20schema%3AalternateName%20%3Falt%3B%0A%20%20%3Fp%20imas%3AIdol.%0A%20%20FILTER(lang(%3Falt)%20%3D%20%27ja%27)%0A%7D)
- [schema:alternateName を持つスタッフ](https://sparql.crssnky.xyz/spql/imas/query?force-accept=text%2Fplain&query=PREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0APREFIX%20imas%3A%20%3Chttps%3A%2F%2Fsparql.crssnky.xyz%2Fimasrdf%2FURIs%2Fimas-schema.ttl%23%3E%0ASELECT%20%3Falt%0AWHERE%20%7B%0A%20%20%3Fs%20schema%3AalternateName%20%3Falt%3B%0A%20%20%3Fp%20imas%3AStaff.%0A%20%20FILTER(lang(%3Falt)%20%3D%20%27ja%27)%0A%7D)

**Comment by foooomio** [comment]
ミリオン以外あまり詳しくないので間違ってたらご指摘ください。

## 本名がわかっているパターン
### ロコ
- `schema:name` に `伴田路子`、`schema:alternateName` に `ロコ` が登録されている。
- `schema:familyName` に `伴田`、 `schema:givenName` に `路子` が登録されている。

## 本名が全くわかっていないパターン
### ジュリア
- `schema:name` はなく、`schema:alternateName` に `ジュリア` が登録されている。
- `schema:familyName` と `schema:givenName` はない。

### アスラン=BBⅡ世
- `schema:name` はなく、`schema:alternateName` に `アスラン=BBⅡ世` が登録されている。
- `schema:familyName` と `schema:givenName` はない。

## 本名が一部わかっているパターン
### 詩花
- `schema:name` はなく、`schema:alternateName` に `詩花` が登録されている。
- `schema:givenName` に `詩花` が登録されている。
- 本名は推測できるが、はっきり言及されていないので `schema:familyName` が登録されていない？

### 玲音
- `schema:name` はなく、`schema:alternateName` に `玲音` が登録されている。
- `schema:givenName` に `玲音` が登録されている。
- 名字の読みは判明している。
- `<schema:name xml:lang="en">Kamiizumi</schema:name>` となっているんですが、`schema:familyName` の間違いでしょうか？

## その他
### エミリー
- `schema:name` に `エミリースチュアート`、`schema:alternateName` に `エミリー` が登録されている。
- カード名などでは「エミリー」、楽曲情報などでは「エミリースチュアート」と、ゲーム内でも混在して使われている。

**Comment by foooomio** [comment]
まとめたつもりが、自分でもよくわからなくなってます(ダメじゃん)。以下、私見です。

- **本名がわかっているパターン**は、`schema:name` と `schema:alternateName` を入れ替えるか、提案のように `imas:realName` を新しく定義するかのどちらかが良いと思います。

- **本名が全くわかっていないパターン**と**本名が一部わかっているパターン**は、`schema:alternateName` を `schema:name` に変えるだけで良いと思います。

エミリーはどうしましょうね・・・？

**Comment by crssnky** [comment]
> - <schema:name xml:lang="en">Kamiizumi</schema:name> となっているんですが、schema:familyName の間違いでしょうか?
間違いです！修正します！

**Comment by crssnky** [comment]
ジャパンサーチという最近できた大きなSPARQLエンドポイントを真似て、xsd:stringの名称rdfs:labelを作ろうと思うのですがどうでしょうか？
https://github.com/imas/imasparql/issues/236#issuecomment-489295586

**Comment by foooomio** [comment]
カードの名称を `rdfs:label` に入れるということですね。良さそうな気がします。

が、例えばロコの英語名を引いたときに `Handa Roco` が返ることになるんでしょうか・・・？

`rdfs:label` 自体には反対しませんが、この件の解決にはならないのではないかと疑問に思いました。

**Comment by crssnky** [comment]
僕のイメージとしては、"活動名=日本語のみ"という感じです。(たぶんこれが一番頻度が高いですし)
なので英語名を引く場合は、適切な述語を引いてもらおうと思っています。
Turtleで実装例を書いてみたのですが、どうでしょうか
```Turtle
imasrdf:Kisaragi_Chihaya  a  imas:Idol
　rdfs:label "如月千早"
　schema:name "如月千早"@ja
　schema:name "Kisaragi Chihaya"@en
　schema:familyName "如月"@ja
　schema:familyName "Kisaragi"@en
　schema:givenName "千早"@ja
　schema:givenName "Chihaya"@en

imasrdf:Handa_Roco  a  imas:Idol
　rdfs:label "ロコ"
　schema:name "伴田路子"@ja
　schema:name "Handa Roco"@en
　schema:familyName "伴田"@ja
　schema:familyName "Handa"@en
　schema:givenName "路子"@ja
　schema:givenName "Roco"@en
　schema:alternateName "ロコ"@ja
　schema:alternateName "Roco"@ja

imasrdf:Julia  a  imas:Idol
　rdfs:label "ジュリア"
　schema:alternateName "ジュリア"@ja
　schema:alternateName "Julia"@ja
```

**Comment by foooomio** [comment]
たしかに英名だけ必要になるケースって想定できないので問題なさそうですね。`schema:*Name` との整合性も取れてきれいですし。

あと問題はエミリーですかね・・・？

**Comment by crssnky** [comment]
活動名としてのrdfs:labelができるのであれば、schema:alternateNameは無くしても良いかもしれないですね。上記例の千早さんと同じ項目になるかと。

**Comment by foooomio** [comment]
ジュリアの `schema:alternateName "Julia"@en` はどうなりますか？`@ja` だけ削って `@en` を残しますか？

**Comment by crssnky** [comment]
あーごめんなさい、コピペミスです…
imasrdf:Julia  a  imas:Idol
　rdfs:label "ジュリア"
　schema:alternateName "ジュリア"@ja
　schema:alternateName "Julia"@en
が正しいです！

**Comment by foooomio** [comment]
`schema:alternateName` をなくすのはロコだけ(もしくは詩花と玲音も？)だけで、ジュリアは残すということですか？

**Comment by crssnky** [comment]
`schema:alternateNme`保持：ロコ・ジュリア・アスラン  
`schema:alternateNme`消し：エミリー・詩花・玲音  
どうでしょう？

**Comment by foooomio** [comment]
`rdfs:label` が芸名の場合は `schema:alternateName` として残す。本名の一部の場合は消す。という線引きですね？いいんじゃないでしょうか。

ちなみに、エミリーの問題というのは `rdfs:label` に「エミリー」か「エミリースチュアート」のどちらを入れるかという問題のつもりでした。言葉足らずでしたね、すみません・・・

**Comment by crssnky** [comment]
エミリーはミリシタのサイトもカードも「エミリー」ですので、`rdfs:label`にはエミリーを入れようと思います

**Comment by foooomio** [comment]
了解です。同意します。
