### ISSUE TITLE
RDFファイルの分割を考える

### ISSUE THREAD

**Issue by oniipon** [imas/imasparql#261]
`Live.rdf` を筆頭に行数が多いファイルがちらほらあるので
なんらかのルールで分割し、CI等でマージ出来る仕組みを考える

- 運用方法
  - どういう粒度で分割するか
  - 全体のディレクトリ構成どうするか

- 技術面
  - どうやってマージするか (普通のテキストファイルと解釈してマージでいいかな)

**Comment by crssnky** [comment]
ファイルが増えても特に問題ので、マージは必要ないですね。
Live.rdfはたしかに行数もかなり増えていく予定なので、各年ごとに分けますか。
例:Live_2020.rdf

**Comment by crssnky** [comment]
@Contributor各位
他にも分割してほしいファイルがあったら書いてください(直接PulReqでも可)
