### ISSUE TITLE
続：一部アイドルの名前が間違っている

### ISSUE THREAD

**Issue by NCT48** [imas/imasparql#285]
また見つけてしまいました。

- 岸部彩華
  - imas:familyNameKanaがきしばになっている
- 氏家むつみ
  - imas:familyNameKanaとschema:givenNameが入れ替わっている
- 赤西瑛梨華
  -  imas:familyNameKanaが漢字のまま
- 乙倉悠貴
  - schema:givenNameとschema:nameの英語がyukiになっている
- イヴ・サンタクロース
  - imas:givenNameKanaがカタカナのまま
- 天道輝
  - imas:familyNameKanaがてんどうてるになっている

ご確認よろしくお願いします。

**Comment by YutaGoto** [comment]
乙倉悠貴(おとくらゆうき)などの長音が入ったときのローマ字表記はどっちに統一されているんですかね..? (yuki, yuuki or something)
四条貴音や西城樹里などなども。。。

**Comment by foooomio** [comment]
カードのフレームでは「YUUKI OTOKURA」となっていますね。
参考: https://imas.gamedbs.jp/cg/idol/detail/198

#277 では同様の理由で、詩花を Shiika → Shika に修正しました。

他にもこのパターンがあるかどうかは洗い出してみないとわからないですね。

**Comment by YutaGoto** [comment]
ふらふらファイルを眺めていたらタイポを見つけましたので、ついでに直してもらえると。。。

https://github.com/imas/imasparql/blob/13d2805872552cdaea386a744495566b4b6a264f/RDFs/283.rdf#L348-L349

**Comment by takemikami** [comment]
ついでに気づくシリーズ、今井加奈のgivenNameが「可奈」になってますね。
https://github.com/imas/imasparql/blob/master/RDFs/CinderellaGirls.rdf#L192

**Comment by NCT48** [comment]
issueを起こす時は、基本的にカードに書かれた名前とくらべてます。

長音の基準に関しては、「ゆうき」と「りいな」は「ゆき」と「りな」がそれぞれいるからだと勝手に解釈してますけど、、、他は分かんないっすね。

**Comment by foooomio** [comment]
追加で
- 道明寺歌鈴 Domyouji → Domyoji
- 難波笑美 Nanba → Namba
- 土屋亜子 Tsutiya → Tsuchiya

@crssnky カード準拠で修正をプルリクに混ぜちゃっても大丈夫ですか？

**Comment by takemikami** [comment]
類似ケース調べたら、他にも以下の誤りがありました。

## RDFs/CinderellaGirls.rdf

伊集院惠の「惠」が旧字体になっていない
https://github.com/imas/imasparql/blob/master/RDFs/CinderellaGirls.rdf#L3018

綾瀬穂乃香の名前が「穂乃果」になってる
https://github.com/imas/imasparql/blob/master/RDFs/CinderellaGirls.rdf#L3161

藤居朋の名字が「藤井」になっている
https://github.com/imas/imasparql/blob/master/RDFs/CinderellaGirls.rdf#L3488

斉藤洋子の名字が旧字体「斎藤」になっている
https://github.com/imas/imasparql/blob/master/RDFs/CinderellaGirls.rdf#L4219

## RDFs/765AS.rdf

高槻やよいのfamilyname@enが日本語
https://github.com/imas/imasparql/blob/master/RDFs/765AS.rdf#L174

## RDFs/283.rdf

田中摩美々の名字が「Yanaka」
https://github.com/imas/imasparql/blob/master/RDFs/283.rdf#L241

**Comment by crssnky** [comment]
@foooomio さん カード準拠でお願いします！！

**Comment by crssnky** [comment]
ご報告、そして修正ありがとうございます！
