### ISSUE TITLE
サイネリア(鈴木彩音)を追加したい

### ISSUE THREAD

**Issue by smicle** [imas/imasparql#297]
サイネリアがなかったので追加したいです。  
`876.rdf`に追加をするのが良いと思ったのですがどうですか？  
名前についてはロコと同様になると思います。

**Comment by smicle** [comment]
追加される場所が決まればPRを飛ばしたいと考えています。

**Comment by crssnky** [comment]
ぜひともお願いしたいです！　876の場所にお願いします！！
