### ISSUE TITLE
SideM 九十九一希の新キャストが決まった

### ISSUE THREAD

**Issue by smicle** [imas/imasparql#329]
徳武竜也から比留間俊哉に変更されました。
キャストの更新と旧キャストの扱いをどうするか。
https://idolmaster.jp/blog/?p=77554

**Comment by crssnky** [comment]
Slackからの転載
> よりオントロジーとかを考えるなら、IdolがCharacterVoiceを持って、CharacterVoiceがVoiceActerと担当期間を持つべき…となるんですかね

> 「現行の声優」ってプロパティと「そのアイドルの役を持った声優（複数いたら全員載せる）」って2つのプロパティを作るとか…？

> 今の声優というのはimas:cvで良くて、それとは別にimas:pastCvみたいなのを作るといい感じになりそうですね

> どちらにせよ、CVのクラスを作ってしまったほうが良さそう
(影響範囲大きそうだけど)

**Comment by crssnky** [comment]
クラスは作らず、pastCvでぶら下げていくので良いですかね...?

**Comment by crssnky** [comment]
とりあえずその方法で行きました
