### ISSUE TITLE
schema:nameの英語リソースが「姓」+「名」の表記順になっている

### ISSUE THREAD

**Issue by subroh0508** [imas/imasparql#357]
ので、個人的には「名」+「姓」の表記順に修正したい。

### 「名」+「姓」順の根拠

- アイマスのカードの英語表記は大体「名」+「姓」の順
- [アイマス英語版wiki](project-imas.com/wiki/Main_Page)の表記も「名」+「姓」の順

### 「姓」+「名」順の根拠

- 日本政府の方針: [日本人の名前ローマ字表記を「姓－名」順に　政府方針](https://www.sankei.com/politics/news/190906/plt1909060011-n1.html) - 産経新聞 2019年09月06日

どうでしょうか 🤔

**Comment by subroh0508** [comment]
因みにcroMisaさんの意見

https://twitter.com/croMisa/status/1271064992289132550

**Comment by crssnky** [comment]
書いた側としてはこだわりはありません。
姓→名のニュースを知っていたのと、主語が姓→名だったのでそのまま写した気がします。
利用側の意見がありましたら、ぜひお願いします。

**Comment by crssnky** [comment]
カードがだいたいそうであれば、「名」「姓」の順番にしますか

**Comment by crssnky** [comment]
一旦閉じます。
元のままが良いという要望がありましたら再オープンしてください
