### ISSUE TITLE
ポップリンクスの属性について

### ISSUE THREAD

**Issue by crssnky** [imas/imasparql#377]
```ttl
imas:Attribute          a   rdf:Property ;
    rdfs:comment            "属性(Vo,Da,Vi)を表すプロパティ" ;
    rdfs:label              "属性"@ja .
```
すでに`属性`は使用済みである。
ポップリンクスのサイトにて、`id="attributeCol"`の記述がなされているため、属性色というプロパティを提案する。公式サイトと乖離してしまう恐れアリ。
```ttl
imas:AttributeColor     a   rdf:Property ;
    rdfs:comment            "属性色(ポップリンクス)を表すプロパティ" ;
    rdfs:label              "属性色"@ja .
```

**Comment by subroh0508** [comment]
重箱の隅をつついてるようで申し訳ないですが、`id="attributeCol"`の`Col`は`Column`のことのような… 🤔

**Comment by crssnky** [comment]
だって！`id="audio_area"`はcol付いてないもん！:cry:

**Comment by crssnky** [comment]
複数あるし、Propertyも良い気がしてきた

**Comment by crssnky** [comment]
実は属性(Vo,Da,Vi)という単語の方が間違えてる説 
ミリオンライブのサイトではタイプと呼ばれているらしい(サイト自体は無くなってて、スクショのみ) 
http://millionlive.blog.fc2.com/blog-entry-2.html
im@sparqlではタイプはCu,Co,Paで使われちゃってるしなぁ...そっちもサイトでタイプって言われてるし。
https://cinderella.idolmaster.jp/

**Comment by crssnky** [comment]
にしこりさん「imas:PopLinkAttribute」でどうだろうか

**Comment by foooomio** [comment]
ポプマス正式リリースにより、属性の日本語名称が明らかになりました。

![ポプマスの属性](https://user-images.githubusercontent.com/1075914/106147747-97e3cf00-61bb-11eb-900c-993629f0ec04.jpg)

現状、公式サイトのソースからとってきた英語の名称を入れていますが、日本語名称を追加または置換してもいいかなと思います。個人的には置換するのがいいかなと考えていますが、いかがでしょうか。

https://github.com/imas/imasparql/blob/a3978214157605e137cdae1605c4fd4cea4c4289/RDFs/765AS.rdf#L45-L46

**Comment by crssnky** [comment]
データの数は多ければ多いほど良いけど、使いやすさで言えば置換ですかね。
でも漢字一文字はなんかアイマスとしてはダサい...(フォントが悪い？

**Comment by foooomio** [comment]
`xml:lang="en"` を残しておいて `xml:lang="ja"` を追加したときに SPARQL がどうなるかですね。`FILTER ( lang(?attr) = "ja" )` とかで絞り込む形になるんですかね。

Vocal/Dance/Visual、Cute/Cool/Passion、Princess/Fairy/Angel とかに慣れてると、確かに漢字一文字に違和感を抱いてしまいますねｗ

**Comment by crssnky** [comment]
> xml:lang="en" を残しておいて xml:lang="ja" を追加したときに SPARQL がどうなるかですね。FILTER ( lang(?attr) = "ja" ) とかで絞り込む形になるんですかね。

ですです。手間はありますが、ユーザーに選択させる形で行きたいです。
