### ISSUE TITLE
シャニ2ndの振替公演の扱い

### ISSUE THREAD

**Issue by subroh0508** [imas/imasparql#384]
中止になった2020年5月の公演と、2021年3月のやりなおしの公演の名前がどうやら一緒らしい 😇 

旧: https://idolmaster.jp/event/shinycolors_2nd.php
新: https://idolmaster-official.jp/live_event/shinycolors_2nd/

該当箇所: https://github.com/imas/imasparql/blob/51a2870042dd3de4e4c262a4e3a2ba8047e2cb10/RDFs/Lives/Live_2020.rdf#L199-L255

2021年の方、Descriptionで区別がつくよう追加した方が良いですかね…？

**Comment by crssnky** [comment]
Descriptionで区別がつくような分け方でお願いします
