### ISSUE TITLE
デレHNYライブが検索できない

### ISSUE THREAD

**Issue by crssnky** [imas/imasparql#391]
https://twitter.com/subroh_0508/status/1352265833184071680

```sparql
SELECT ?name
WHERE {
  ?live rdf:type imas:Live;
    schema:name ?name;
  FILTER regex(?name, 'THE IDOLM@STER CINDERELLA GIRLS', 'i')
}

```

他のライブ名との相違点として、`&`が含まれているため、`&amp;`に加工しているが、同じ加工を施された`「ぷちます!」トーク&amp;ライブイベント ぷちます!かんしゃさい!!`は検索できるため、なんもわからん。
```sparql
SELECT ?name
WHERE {
  ?live rdf:type imas:Live;
    schema:name ?name;
  FILTER regex(?name, 'ぷちます', 'i')
}
```

**Comment by subroh0508** [comment]
`Lives/Live_2021.rdf`が丸ごとうまいことデプロイできてない？とかですかね

**Comment by crssnky** [comment]
それだーーー！！！
https://crssnky.hatenablog.jp/entry/2020/11/09/234849
これの設定ファイルの言及してるところで2021年を追加してないでした

**Comment by crssnky** [comment]
done.
