### ISSUE TITLE
スタマス新アイドル・奥空心白

### ISSUE THREAD

**Issue by subroh0508** [imas/imasparql#397]
既存ブランドのどこにも属さない説、どうしましょ 😇 

(公式サイト更新され次第、descriptionにリンクを追記)

**Comment by crssnky** [comment]
一旦、判明しているものだけ入れましょうか。プレイで明らかになっていくでしょう(まだニコ生見てない

**Comment by crssnky** [comment]
SHACLでimas:TitleのminCountが1になっているので、入れないという選択肢は無いらしい....
スタマスの登場で時代が変わったということで、この制約を取ってしまう？

ref. #398

**Comment by foooomio** [comment]
#398 マージされたので Close しますね。
