### ISSUE TITLE
シャニマス新アイドル・斑鳩ルカ

### ISSUE THREAD

**Issue by subroh0508** [imas/imasparql#406]
シャニマスに新たに追加されたけど283プロ所属じゃない子 😇 

https://shinycolors.idolmaster.jp/idol/other/luca.html

**Comment by crssnky** [comment]
シャニにしか出ないだろうし、一旦シャニのファイルに追加しますか

**Comment by subroh0508** [comment]
@crssnky `imas:Title`もとりあえず`283pro`にしておく感じですかね…？ 👀

**Comment by crssnky** [comment]
`imas:Brand`が利用できるようになったためよろしくおねがいします
