### ISSUE TITLE
ユニットの登場メディア

### ISSUE THREAD

**Issue by tankarup** [imas/imasparql#419]
コミックオリジナルのユニットも登録されているので、データの追加を考えています(ミリオンライブBNSなど)。

ただ、ゲーム本編に登場しないユニットは馴染みがないことも多く、どんなメディアに登場したユニットなのか記載したほうがよいのではないかと感じました。

ユニットが登場したメディアを記載することは可能でしょうか？

**Comment by crssnky** [comment]
"メディア"となると、いわゆるimas_product系になるかと思います。
そちらに記載して、rdf:resourceとしてユニットを指定する形が良いかもしれません。

僕含め、誰にも馴染みのないimas_product系の説明をさせていただきます。
`https://sparql.crssnky.xyz/spql/imas_product/query`(imas/queryではなく、imas_product/queryになっている)をエンドポイントに持つ、現実世界(我々)から見たアイマス作品を表すSPARQLデータベースとなっています。
いつものim@sparqlは、ロールプレイ的に向こうの世界で閉じて、向こうの世界のみで完結する情報を記載しています(利便性のためC.V.等の例外有り)。

#409 にある通り、一度imas_product系を整備しますので、併せて記載できるものを用意しようかと思います。
出典は確かにあると便利ですもんね！

**Comment by tankarup** [comment]
お返事ありがとうございます。まずはimas_productを先に整備してから、ということですね。では、登場メディアはデータが整備された後に追記したいと思います。

なお"imas_product"というくくりですと、これらのユニットの扱いが少し難しいように思いました。
・ニコニコ超音楽祭：蒼黒の美声楽団、はいさいフューチャースター
・ミリラジ まえのり!!：ゆきすべり、ちくわみながら、…
・ラジオdeアイマSTAR☆：cheffle
・ラジオdeアイマSHOW!： TORICO, Engage!
個人的には、これらのユニットはアイドルユニットというよりアイマス声優ユニットのようにも見えます。ライブと同じように、声優名での記載に変更するのはどうでしょうか？　番組内でどのような扱いであったのか分からないので、声優名がよいのかアイドル名がよいのか判断つきませんが。

**Comment by crssnky** [comment]
超音楽祭はアイドルの名義として参加しているという認識です。`hogeUnit(○○(C.V.△△)、....)`のような感じ。
ミリラジまえのりは、ラジオ内でコミュがあったのでユニットでしょう(甘い判定)。
アイマSTAR/SHOWは、僕がPになる以前の話なので分かりませんが、ラジオ内でユニットとして活動してる風なコミュがあったのではないでしょうか。

**Comment by tankarup** [comment]
ガイドライン的なものが欲しいなぁと思いながら質問させていただいたのですが、番組の内容を実際に見て個別に判断しなければならないということですね。ありがとうございました。
