### ISSUE TITLE
ポプマス追加実装アイドルの属性について

### ISSUE THREAD

**Issue by HagiAyato** [imas/imasparql#439]
ポプマス登場アイドルの属性について、初期実装以降追加実装となったアイドルの属性がDB未登録です。
追加していただけますでしょうか。

- 参考：https://gamerch.com/poplinks/entry/217440

以下の動画以降の追加アイドルです。
https://www.youtube.com/watch?v=oRAqnt4ScSk

※ラベルは付け方不明のためつけておりませんが、"追加するだけ "に当たります

**Comment by HagiAyato** [comment]
考えてみれば今後も追加実装アイドルは多数出ることとなるので、このissueには"継続的追加が必要"ラベルもつける必要がありますね。

**Comment by YutaGoto** [comment]
自動で追加するような仕組みは難しいので、気づいた方がプルリクを出して追加する運用でよいかと思います！
現に追加してくださってありがとうございます :bow:
