### ISSUE TITLE
浅利七海ちゃんの CV が発表されました

### ISSUE THREAD

**Issue by 346chihiro1128** [imas/imasparql#461]
お疲れ様です、プロデューサーさん。
本日、[浅利七海](https://dic.nicovideo.jp/id/5206363)ちゃんの CV が発表されました。
- [井上ほの花](https://dic.nicovideo.jp/id/5428557)

ご確認よろしくお願いしますね。

**Comment by foooomio** [comment]
#460

**Comment by 346chihiro1128** [comment]
:smile::+1:
