### ISSUE TITLE
日本語フィールドのxml:lang属性が統一されていない

### ISSUE THREAD

**Issue by gomao9** [imas/imasparql#49]
RDFの日本語フィールドが `xml:lang="ja"` だったり `xml:lang="jp"` だったりして統一されていません。
国ではなく言語ですので、 `ja` のほうが正しいと思うのでそちらへ統一すべきかと思います。
（使い分けに何か意図があったらごめんなさい）

**Comment by crssnky** [comment]
すみません、意図無いです！
修正します

**Comment by crssnky** [comment]
xml:lang属性付ける時は、rdf:datatype付けちゃダメみたいです。
xml:lang属性のところは、rdf:datatype消します。

**Comment by crssnky** [comment]
修正しました。
