### ISSUE TITLE
施設データに346プロがない

### ISSUE THREAD

**Issue by YutaGoto** [imas/imasparql#508]
https://github.com/imas/imasparql/blob/6fe399d102580e4b1e14d309070749d6e9983401/RDFs/Facility.rdf

シンデレラガールズに登場する事務所の名前・寮の名前が346でいいのかわからないですが。。

**Comment by crssnky** [comment]
めっちゃ分かるけど、プロダクション名はユーザー自身が決められちゃうので…

**Comment by YutaGoto** [comment]
ゲームの世界ではそうでしたね。。。。
