### ISSUE TITLE
秋月涼は同一人物か

### ISSUE THREAD

**Issue by crssnky** [imas/imasparql#9]
現在は秋月涼のURIを男女兼用としているが、分けるべきか
同じにする問題点として、同じ人物だが、プロフィールが2つ出てしまう(876用・315用)。
分けてしまうと、同じ人物としてリンクすることが難しくなる。

**Comment by crssnky** [comment]
とりあえず同じ人物で運用

**Comment by gomao9** [comment]
秋月涼の性別と身長を取得したいと思って下記のようなクエリを発行した場合、4レコードが取得できてしまい、（im@sparql上は）どの組み合わせが正しいのかわからなくなってしまいます。

```
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX imas: <https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT *
WHERE {
  ?idol rdf:type imas:Idol;
    schema:name ?name;
    schema:gender ?gender;
    schema:height ?height.
  FILTER (str(?name) = "秋月涼").
}
```

![image](https://user-images.githubusercontent.com/559370/54926940-a7a58300-4f54-11e9-9e63-679bc304d2a3.png)

DSの秋月涼とSideMの秋月涼を区別できるようなデータ構造、あるいはクエリの工夫があれば教えていただきたいです……

**Comment by gomao9** [comment]
（ちなみにDSの秋月涼は女性扱いで良いのか……？ というのは別の話ですね……）

**Comment by crssnky** [comment]
やっぱダメですよねー！(分かってて解決を延ばしていた人)  
URIに`[アイドル名]_[1st的な接尾辞]`を付けて、分割すべきですね。  
ついでに765AS勢の1stVisionのプロフィールも付ける感じで。  
`[1st的な接尾辞]`って何が良いんでしょう.....普通に`_1st`って付ければ、3rdVisionになっても古いのは`_2nd`で済みそう...?

**Comment by crssnky** [comment]
DS秋月涼のプロフィールは、B値を盛っている(だろう)数値ですし虚偽のプロフィールで突き通します

**Comment by twoterabytes** [comment]
モバマスの特訓前後とかカード別でプロフィールの変化するアイドルの存在を考えると大変な作業になりそうです…(違うレイヤーの話だけど補足として

**Comment by gomao9** [comment]
DSは実は2ndVisionの作品なので、秋月涼の接尾辞には作品名もしくは事務所名を使うのが良いと思います。
765ASに関しては、作品ごとに微妙にプロフィールが違う（特に趣味）と記憶しているので、大変かもしれないですね……。大雑把に分けると、1stVision,2ndVision,ミリオンライブ、になるでしょうか。

モバはtwoterabytesさんのおっしゃる通り、特訓前後を記録しようとすると物量が大変なことになりそうです……

**Comment by twoterabytes** [comment]
実は私もあまり詳しくなくて…
試しにきらりさんについて調べたところ、モバでの初期Rとデレステが一致、モバはモバで一定まで変化し続けている(いた)ようです

**Comment by twoterabytes** [comment]
https://dic.pixiv.net/a/%E8%AB%B8%E6%98%9F%E3%81%8D%E3%82%89%E3%82%8A　を見ると、7種類のプロフがある、らしいです

**Comment by gomao9** [comment]
涼だけでも早めに対応したいのでPR出しました #219

**Comment by crssnky** [comment]
タイトルに関することは一旦終わったので、こちらは閉じます。
成長中や1stVision問題は別に立てます
