### ISSUE TITLE
プロデューサーのURI

### ISSUE THREAD

**Issue by crssnky** [imas/imasparql#92]
#85 でも使いたいし、プロフィールが空でも作っておけば何かと使えそう

**Comment by crssnky** [comment]
また追加したいものがあったらreopen

**Comment by HagiAyato** [comment]
プロフィールは今空ですが、
    <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">プロデューサー</rdfs:label>
    <schema:position xml:lang="ja">プロデューサー</schema:position>
    <schema:alternateName xml:lang="ja">プロデューサー</schema:alternateName>
    <schema:alternateName xml:lang="en">Producer</schema:alternateName>
これらについてはどんなPでも共通のため登録してもいいのかなと感じました。
